spring:
  cloud:
    function:
      definition: orderingEventConsumer;orderingEventProducer
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        orderingEventConsumer-in-0:
          destination: data_stream
          group: eventConsumer-dev-local
        orderingEventProducer-out-0:
          destination: data_stream